# Travis CI config:
# running from python script (single line)
language: python
python:
  - "3.6"
os: linux
script:
  - script/test.py --rebuild
sudo: required

git:
  submodules: true

addons:
  apt:
    packages:
      - cmake-data
      - cmake

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install gcc-6 g++-6 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 50
