language: python
python:
  - "3.6"
os: linux
script:
  - script/test.py
sudo: required

git:
  submodules: true

addons:
  apt:
    packages:
      - cmake-data
      - cmake

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install gcc-6 g++-6 -y
